### ISSUE TITLE
La detection des coins fonctionnent uniquement pour les pieces simple

### ISSUE THREAD

**Issue by naulan-chrzaszcz** [naulan-chrzaszcz/blokus#9]
```
■■■■■■■■■■■■■■■■■■■■■■
■■                 ■■■
■■■                ■■■
■ ■  ■               ■
■  ■■■               ■
■                    ■
■                    ■
■                    ■
■                    ■
■                    ■
■                    ■
■                    ■
■                    ■
■                    ■
■                    ■
■                    ■
■                 ■■ ■
■                ■■ ■■
■                   ■■
■                   ■■
■■■■                ■■
■■■■■■■■■■■■■■■■■■■■■■
 Où voulez-vous la placer > 
confirm
Coord invalid
Votre piece n'est pas dans un coin d'une autre piece
```
Quand la piece peut avoit plusieur bottom_right, le code n'en prend que un et oublie les autres possibiliter

**Comment by naulan-chrzaszcz** [comment]
Mettre en oeuvre une liste de coins pour chaque position (top_left, bottom_left, ...).

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the __get_extremities method in the Piece class to store multiple corners when they exist. This change allows the piece to consider all possible corner positions when placing it on the board.

You can review changes in this commit: https://github.com/mnmnk43434/naulan-chrzaszcz-blokus-9/commit/431a5c884892cf8db26cd98c8d2578d6dc4e3736.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
